import Head from "next/head";
import BreadCrumbs from "../../../components/expressPage/BreadCrumbs";
import ExpressHeader from "../../../components/generalComponents.js/ExpressHeader";
import ProductCard from "../../../components/expressPage/subcomponents/ProductCard";
import ProTitle from "../../../components/expressPage/subcomponents/ProTitle";

function Shop() {
  return (
    <div className="bg-gray-50 min-h-screen">
      <Head>
        <title>Portal || Shop </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/MM_Logo.png" />
      </Head>
      <ExpressHeader portal />
      <BreadCrumbs
        title="Products"
        subTitle="Baby & Childcare"
        href="/portal/shop"
      />
      <ProTitle />
      <div
        className="
      container grid gap-4 grid-cols-2 md:grid-cols-4 
      lg:grid-cols-6 
      "
      >
        {Array(24)
          .fill()
          .map((_, i) => (
            <ProductCard
              grid
              key={i}
              name={"Codine Expectorant"}
              src={"/codine.png"}
              price={"$310"}
              discountPrice={"$345"}
              percentDiscount={"10%"}
              href={`/portal/shop/product/Codine Expectorant`}
            />
          ))}
      </div>
    </div>
  );
}

export default Shop;
