import Head from "next/head";
import ExpressHeader from "../../../components/generalComponents.js/ExpressHeader";
import NavCat from "../../../components/expressPage/NavCat";
import ProductSlide from "../../../components/expressPage/ProductSlide";

function index() {
  return (
    <div className="bg-gray-50 min-h-screen">
      <Head>
        <title>Portal || Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/MM_Logo.png" />
      </Head>
      <ExpressHeader portal />
      <NavCat />
      <div
        className="
      grid gap-4 py-4
      "
      >
        <ProductSlide title="Baby & Childcare" recent portal />
        <ProductSlide title="Men Care" />
        <ProductSlide title="Controlled Drugs" discount recent portal />
        <ProductSlide title="Herbal Remedies" discount portal />
        <ProductSlide title="Women Care" portal />
        <ProductSlide title="Deals of the Day" discount portal />
      </div>
    </div>
  );
}

export default index;
