import Head from "next/head";
import CategoriesBanner from "../../components/expressPage/CategoriesBanner";
import AdvertBanner from "../../components/expressPage/AdvertBanner";
import ProductSlide from "../../components/expressPage/ProductSlide";
import ExpressHeader from "../../components/generalComponents.js/ExpressHeader";
import Dashboard from "../../components/portalPage/dashboard";
import { useDispatch, useSelector } from "react-redux";
import { useEffect, useLayoutEffect } from "react";
import { getCategoryRequest, getProductsRequest } from "../../redux/actions";

function index() {
  const dispatch = useDispatch();

  const {
    getCategorySuccess,
    getCategoryError,
    getCategoryLoading,
    categories,
    getProductsLoading,
    products,
  } = useSelector((state) => {
    const {
      success: { getCategory: getCategorySuccess },
      errors: { getCategory: getCategoryError },
    } = state.ajaxStatuses;

    const { getCategoryLoading, getProductsLoading } = state.loadingIndicator;

    const { categories } = state.categoryData;
    const { products } = state.productData;

    return {
      getCategorySuccess,
      getCategoryError,
      getCategoryLoading,
      categories,
      getProductsLoading,
      products,
    };
  });

  useEffect(() => {
    dispatch(getCategoryRequest());
    dispatch(getProductsRequest());
  }, [getCategoryRequest, getProductsRequest]);

  return (
    <div className="bg-gray-50 min-h-screen">
      <Head>
        <title>Portal </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/MM_Logo.png" />
      </Head>
      <ExpressHeader />
      <Dashboard />
      <CategoriesBanner loading={getCategoryLoading} categories={categories} />
      <div className="grid gap-4">
        {!getCategoryLoading &&
          !getProductsLoading &&
          categories
            .slice(0, 6)
            .map((cat) => (
              <ProductSlide
                loading={getCategoryLoading}
                productLoading={getProductsLoading}
                title={cat.name}
                products={products}
              />
            ))}
      </div>
      <AdvertBanner />
    </div>
  );
}

export default index;
