import Head from "next/head";
import ExpressHeader from "../../../components/generalComponents.js/ExpressHeader";
import CustomerSupport from "../../../components/expressPage/supportPage/CustomerSupport";

function index() {
  return (
    <div className="bg-gray-50 min-h-screen">
      <Head>
        <title>Customer Support </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/MM_Logo.png" />
      </Head>
      <ExpressHeader portal />
      <CustomerSupport />
    </div>
  );
}

export default index;
