export const DISPATCH_ERROR = "DISPATCH_ERROR";
export const CLEAR_ERROR_STATE = "CLEAR_ERROR_STATE";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_LOADING = "LOGIN_LOADING";

export const LOGOUT = "LOGOUT";

export const POST_TOKEN_REFRESH_SUCCESS = "POST_TOKEN_REFRESH_SUCCESS";
export const POST_TOKEN_REFRESH_FAIL = "POST_TOKEN_REFRESH_FAIL";
export const POST_TOKEN_REFRESH_REQUEST = "POST_TOKEN_REFRESH_REQUEST";
export const POST_TOKEN_REFRESH_LOADING = "POST_TOKEN_REFRESH_LOADING";

export const POST_UPDATE_USER_SUCCESS = "POST_UPDATE_USER_SUCCESS";
export const POST_UPDATE_USER_FAIL = "POST_UPDATE_USER_FAIL";
export const POST_UPDATE_USER_REQUEST = "POST_UPDATE_USER_REQUEST";
export const POST_UPDATE_USER_LOADING = "POST_UPDATE_USER_LOADING";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_LOADING = "REGISTER_LOADING";

export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAIL = "GET_CATEGORY_FAIL";
export const GET_CATEGORY_REQUEST = "GET_CATEGORY_REQUEST";
export const GET_CATEGORY_LOADING = "GET_CATEGORY_LOADING";

export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";
export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_LOADING = "GET_PRODUCTS_LOADING";

export const GET_CAT_PRODUCTS_SUCCESS = "GET_CAT_PRODUCTS_SUCCESS";
export const GET_CAT_PRODUCTS_FAIL = "GET_CAT_PRODUCTS_FAIL";
export const GET_CAT_PRODUCTS_REQUEST = "GET_CAT_PRODUCTS_REQUEST";
export const GET_CAT_PRODUCTS_LOADING = "GET_CAT_PRODUCTS_LOADING";

export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";
export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_LOADING = "GET_PRODUCT_LOADING";
