import Head from "next/head";
import ExpressHeader from "../../../components/generalComponents.js/ExpressHeader";
import SettingNav from "../../../components/expressPage/settingsPage/SettingNav";
import { useState } from "react";
import SetBar from "../../../components/portalPage/settings/SetBar";
import EditProfile from "../../../components/portalPage/settings/EditProfile";
import ChangePassword from "../../../components/portalPage/settings/ChangePassword";
import Legals from "../../../components/portalPage/settings/Legals";
import PaymentOptions from "../../../components/portalPage/settings/PaymentOptions";
import { usePortalSetTabState } from "../../../store";

function index() {
  const { currentId } = usePortalSetTabState();

  const setComponet = [
    {
      Content: EditProfile,
      id: 0,
      name: "Edit Profile",
    },
    {
      Content: ChangePassword,
      id: 1,
      name: "Change Password",
    },
    {
      Content: Legals,
      id: 2,
      name: "Legal Documents",
    },
    {
      Content: PaymentOptions,
      id: 3,
      name: "Bank Details",
    },
  ];

  return (
    <div className="bg-gray-50 min-h-screen">
      <Head>
        <title>midlman || portal || settings </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/MM_Logo.png" />
      </Head>
      <ExpressHeader portal />
      <SettingNav currentId={currentId} tabData={setComponet} portal />
      <SetBar tabData={setComponet} />
      <div className="py-4">
        {setComponet.map(
          ({ Content, id }) => id === currentId && <Content key={id} />
        )}
      </div>
    </div>
  );
}

export default index;
