import Head from "next/head";
import Login from "../../../../components/expressPage/login";

function index() {
  return (
    <div className="bg-gray-50 min-h-screen">
      <Head>
        <title>express || login </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/MM_Logo.png" />
      </Head>
      <Login />
    </div>
  );
}

export default index;
