import Head from "next/head";
import ExpressHeader from "../../../components/generalComponents.js/ExpressHeader";
import HelpHead from "../../../components/helpPage/HelpHead";
import Questions from "../../../components/helpPage/Questions";

function index() {
  return (
    <div className="bg-gray-50 min-h-screen">
      <Head>
        <title>midlman || help </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/MM_Logo.png" />
      </Head>
      <ExpressHeader />
      <HelpHead />
      <Questions />
    </div>
  );
}

export default index;
