import Head from "next/head";
import AdvertBanner from "../../components/expressPage/AdvertBanner";
import Banner from "../../components/expressPage/Banner";
import BrandSlides from "../../components/expressPage/BrandSlides";
import CallGrid from "../../components/expressPage/CallGrid";
import CategoriesBanner from "../../components/expressPage/CategoriesBanner";
import ExpressHeader from "../../components/generalComponents.js/ExpressHeader";
import NavCat from "../../components/expressPage/NavCat";
import ProductSlide from "../../components/expressPage/ProductSlide";
import { useDispatch, useSelector } from "react-redux";
import { useEffect, useLayoutEffect } from "react";
import { getCategoryRequest, getProductsRequest } from "../../redux/actions";

function index() {
  const dispatch = useDispatch();

  const {
    getCategorySuccess,
    getCategoryError,
    getCategoryLoading,
    categories,
    getProductsLoading,
    products,
  } = useSelector((state) => {
    const {
      success: { getCategory: getCategorySuccess },
      errors: { getCategory: getCategoryError },
    } = state.ajaxStatuses;

    const { getCategoryLoading, getProductsLoading } = state.loadingIndicator;

    const { categories } = state.categoryData;
    const { products } = state.productData;

    return {
      getCategorySuccess,
      getCategoryError,
      getCategoryLoading,
      categories,
      getProductsLoading,
      products,
    };
  });

  useEffect(() => {
    dispatch(getCategoryRequest());
    dispatch(getProductsRequest());
  }, [getCategoryRequest, getProductsRequest]);

  return (
    <div className="bg-gray-50">
      <Head>
        <title>midlman || Express </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/MM_Logo.png" />
      </Head>

      <ExpressHeader />
      <NavCat loading={getCategoryLoading} categories={categories} />
      <Banner />
      <CallGrid />
      <CategoriesBanner loading={getCategoryLoading} categories={categories} />
      <div
        className="
      flex flex-col space-y-2 py-4 
      "
      >
        {!getCategoryLoading &&
          !getProductsLoading &&
          categories
            .slice(0, 6)
            .map((cat) => (
              <ProductSlide
                loading={getCategoryLoading}
                productLoading={getProductsLoading}
                title={cat.name}
                products={products}
              />
            ))}
      </div>
      <AdvertBanner />
      <BrandSlides />
      <div
        className="
      grid gap-2 pt-4 pb-6 
      "
      >
        {/* {data?.response.slice(3).map(({ name }) => (
          <ProductSlide title={name} />
        ))} */}
      </div>
    </div>
  );
}

export default index;
