import Head from "next/head";
import BreadCrumbs from "../../../components/expressPage/BreadCrumbs";
import ExpressHeader from "../../../components/generalComponents.js/ExpressHeader";
import ProductCard from "../../../components/expressPage/subcomponents/ProductCard";
import ProTitle from "../../../components/expressPage/subcomponents/ProTitle";
import { useRouter } from "next/router";
import { useDispatch, useSelector } from "react-redux";
import { useEffect } from "react";
import { getCatProductsRequest } from "../../../redux/actions";

function Shop() {
  const router = useRouter();
  const { query } = router;

  const dispatch = useDispatch();

  const {
    getCatProductsSuccess,
    getCatProductsError,
    getCatProductsLoading,
    products,
  } = useSelector((state) => {
    const {
      success: { getCatss: getCatProductsSuccess },
      errors: { getCatProducts: getCatProductsError },
    } = state.ajaxStatuses;

    const { getCatProductsLoading } = state.loadingIndicator;

    const { products } = state.productData;

    return {
      getCatProductsSuccess,
      getCatProductsError,
      getCatProductsLoading,
      products,
    };
  });

  useEffect(() => {
    if (query.id) {
      dispatch(getCatProductsRequest(query.id));
    }
  }, [query.id]);

  return (
    <div className="bg-gray-50 min-h-screen">
      <Head>
        <title>express || Shop </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/MM_Logo.png" />
      </Head>
      <ExpressHeader />
      <BreadCrumbs title="Products" subTitle={query.id} href="/express/shop" />
      <ProTitle title={query.id} />
      <div
        className="
      container grid gap-4 grid-cols-2 md:grid-cols-4
      lg:grid-cols-6
      "
      >
        {!getCatProductsLoading &&
          products.map((product, i) => (
            <ProductCard
              grid
              key={i}
              data={product}
              src={product.image ? product.image[0] : "/codine.png"}
              discountPrice={"$345"}
              percentDiscount={"10%"}
            />
          ))}
      </div>
    </div>
  );
}

export default Shop;
