import Head from "next/head";
import BreadCrumbs from "../../../../components/expressPage/BreadCrumbs";
import ExpressHeader from "../../../../components/generalComponents.js/ExpressHeader";
import ProductDescription from "../../../../components/expressPage/ProductDescription";
import { useRouter } from "next/router";
import { useDispatch, useSelector } from "react-redux";
import { useEffect } from "react";
import { getProductRequest } from "../../../../redux/actions";

function Product() {
  const router = useRouter();
  const { query } = router;

  const dispatch = useDispatch();

  const { getProductSuccess, getProductError, getProductLoading, product } =
    useSelector((state) => {
      const {
        success: { getProduct: getProductSuccess },
        errors: { getProduct: getProductError },
      } = state.ajaxStatuses;

      const { getProductLoading } = state.loadingIndicator;

      const { product } = state.productData;

      return {
        getProductSuccess,
        getProductError,
        getProductLoading,
        product,
      };
    });

  useEffect(() => {
    if (query.id) {
      dispatch(getProductRequest(query.id));
    }
  }, [query.id]);

  return (
    <div className="bg-gray-50 min-h-screen">
      <Head>
        <title>midlman || Shop </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/MM_Logo.png" />
      </Head>
      <ExpressHeader />
      <BreadCrumbs
        title="Home"
        subTitle="Product Decsription"
        href="/express"
      />
      {!getProductLoading && <ProductDescription data={product} />}
    </div>
  );
}

export default Product;
