import Head from "next/head";
import ExpressHeader from "../../../components/generalComponents.js/ExpressHeader";
import Order from "../../../components/expressPage/ordersPage/Order";
import OrderHead from "../../../components/expressPage/ordersPage/OrderHead";

function index() {
  return (
    <div className="bg-gray-50 min-h-screen">
      <Head>
        <title>midlman || order </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/MM_Logo.png" />
      </Head>
      <ExpressHeader portal />
      <OrderHead />
      <div className="grid gap-2">
        <Order status="PENDING" />
        <Order status="PENDING" />
        <Order status="PROCESSING" />
        <Order status="COMPLETED" />
      </div>
    </div>
  );
}

export default index;
