import Head from "next/head";
import ExpressHeader from "../../../components/generalComponents.js/ExpressHeader";
import ResetPwd from "../../../components/expressPage/settingsPage/ResetPwd";
import SetBar from "../../../components/expressPage/settingsPage/SetBar";
import SetProfile from "../../../components/expressPage/settingsPage/SetProfile";
import SettingNav from "../../../components/expressPage/settingsPage/SettingNav";
import { useExpressSetTabState } from "../../../store";
import protectedRoute from "../../../components/higherOrderComponents/protectedRoute";

function index({}) {
  const { currentId } = useExpressSetTabState();

  const setComponet = [
    {
      Content: SetProfile,
      id: 0,
      name: "Edit Profile",
    },
    {
      Content: ResetPwd,
      id: 1,
      name: "Change Password",
    },
  ];

  return (
    <div className="bg-gray-50 min-h-screen">
      <Head>
        <title>express || settings </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/MM_Logo.png" />
      </Head>
      <ExpressHeader />
      <SettingNav currentId={currentId} tabData={setComponet} />
      <SetBar tabData={setComponet} />

      {setComponet.map(
        ({ Content, id }) => id === currentId && <Content key={id} />
      )}
    </div>
  );
}

export default protectedRoute(index);
