import Head from "next/head";
import AboutUs from "../components/aboutPage/AboutUs";
import Mission from "../components/aboutPage/Mission";
import Possibilities from "../components/aboutPage/Possibilities";
import Team from "../components/aboutPage/Team";
import Header from "../components/landingPage/Header";
import Footer from "../components/landingPage/Footer";
import Contact from "../components/landingPage/Contact";
import onAboutPageData from "../contents/onAboutPage";

function about() {
  return (
    <div className="relative">
      <Head>
        <title>midlman || About-Us </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/MM_Logo.png" />
      </Head>
      <Header />
      <AboutUs />

      {onAboutPageData.ourPurposeData.map(({ title, text, imgSrc }, i) => (
        <Mission
          vision={i === 1}
          heading={title}
          url={imgSrc}
          caption={text}
          key={i}
        />
      ))}

      <Possibilities />
      <Team />
      <Contact />
      <Footer />
    </div>
  );
}

export default about;
