import Header from "../components/landingPage/Header";
import Footer from "../components/landingPage/Footer";
import Head from "next/head";
import BlogHead from "../components/blogPage/BlogHead";
import BlogSlides from "../components/blogPage/BlogSlides";
import BlogGrid from "../components/blogPage/BlogGrid";

function blog() {
  return (
    <div className="relative bg:gray-100">
      <Head>
        <title>midlman || Blog </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/MM_Logo.png" />
      </Head>
      <Header />
      <BlogHead />
      <BlogSlides />
      <BlogGrid />
      <Footer />
    </div>
  );
}

export default blog;
