import Header from "../components/landingPage/Header";
import Footer from "../components/landingPage/Footer";
import Head from "next/head";
import ContactHeading from "../components/contactPage/ContactHeading";
import Contact from "../components/landingPage/Contact";

function contact() {
  return (
    <div className="relative">
      <Head>
        <title>midlman || contact </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/MM_Logo.png" />
      </Head>
      <Header />
      <ContactHeading />
      <Contact />
      <Footer />
    </div>
  );
}

export default contact;
