import Header from "../components/landingPage/Header";
import Footer from "../components/landingPage/Footer";
import Head from "next/head";
import Cookie from "../components/landingPage/Cookie";

function cookies() {
  return (
    <div className="min-h-screen">
      <Head>
        <title>midlman || Cookies-Policy </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/MM_Logo.png" />
      </Head>
      <Header />
      <Cookie />
      <Footer />
    </div>
  );
}

export default cookies;
