import Head from "next/head";
import Header from "../components/landingPage/Header";
import Hero from "../components/landingPage/Hero";
import TrustArea from "../components/landingPage/TrustArea";
import WhatWeDo from "../components/landingPage/WhatWeDo";
import Comment from "../components/landingPage/Comment";
import ServiceNumber from "../components/landingPage/ServiceNumber";
import HealthSector from "../components/landingPage/HealthSector";
import OwnBusiness from "../components/landingPage/OwnBusiness";
import BolgGallery from "../components/landingPage/BolgGallery";
import GetApp from "../components/landingPage/GetApp";
import Footer from "../components/landingPage/Footer";
import Contact from "../components/landingPage/Contact";
import Testimonial from "../components/landingPage/Testimonial";
import dataOnLandingPage from "../contents/onLandingPage";
import { useEffect } from "react";
import { usePortalPageState } from "../store";

export default function Home() {
  const { setOnPortal } = usePortalPageState();

  useEffect(() => {
    setOnPortal(false);
  }, []);

  return (
    <div className="min-h-sreen bg-green-sub3">
      <Head>
        <title>midlman</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/MM_Logo.png" />
      </Head>
      <Header />
      <Hero />
      <TrustArea />
      <WhatWeDo />
      <Comment />
      <ServiceNumber />
      <HealthSector />
      {dataOnLandingPage?.ownBusinessData?.map(
        ({ title, name, btn, href, subTitle, catlogs, img1, img2 }, i) => (
          <OwnBusiness
            title={title}
            name={name}
            btn={btn}
            href={href}
            subTitle={subTitle}
            catlogs={catlogs}
            img1={img1}
            img2={img2}
            key={i}
          />
        )
      )}

      <BolgGallery />
      <Testimonial />
      <GetApp />
      <Contact />
      <Footer />
    </div>
  );
}
