import Header from "../components/landingPage/Header";
import Footer from "../components/landingPage/Footer";
import Head from "next/head";
import SupportHead from "../components/supportPage/SupportHead";
import Customer from "../components/supportPage/Customer";
import supportData from "../contents/onSupportPage";

function support() {
  return (
    <div className="">
      <Head>
        <title>midlman || support </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/MM_Logo.png" />
      </Head>
      <Header />
      <SupportHead />
      {supportData.map(({ title, text, btnText, src }, i) => (
        <Customer
          //add start props if remainder of i/2 equals 1 thus making odd numbers true
          start={i % 2 === 1}
          title={title}
          text={text}
          btnText={btnText}
          src={src}
          key={i}
        />
      ))}
      <Footer />
    </div>
  );
}

export default support;
