import Head from "next/head";
import Register from "../../../components/expressPage/login/Register";

function index() {
  return (
    <div className="bg-gray-50 min-h-screen">
      <Head>
        <title>express || register </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/MM_Logo.png" />
      </Head>
      <Register />
    </div>
  );
}

export default index;
