import Head from "next/head";
import ExpressHeader from "../../../components/generalComponents.js/ExpressHeader";
import Prescription from "../../../components/expressPage/Prescription/Index";

function index() {
  return (
    <div className="bg-gray-50">
      <Head>
        <title>express || prescriptions </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/MM_Logo.png" />
      </Head>
      <ExpressHeader />
      <Prescription />
    </div>
  );
}

export default index;
